'use strict';
module.exports = app => {
    // app.get('/courseTable/getTableByTeacherId', 'courseTable.getTableByTeacherId');
  app.post('/courseTable/add', 'courseTable.courseTable.add');
  app.post('/courseTable/getMakeUpStudents', 'courseTable.courseTable.getMakeUpStudents');
  app.post('/courseTable/update', 'courseTable.courseTable.update');

  app.get('/courseTable/getClassTimeClassById', 'courseTable.courseTableDetail.getClassTimeClassById');
  app.post('/courseTable/copy', 'courseTable.courseTable.copy');
  app.get('/courseTable/getBaseData', 'courseTable.courseTable.getBaseData');
  app.get('/courseTable/getById', 'courseTable.courseTable.getById');
  app.get('/courseTable/getByTeacherId', 'courseTable.courseTable.getByTeacherId');
  app.get('/courseTable/getWeekItemsForWx', 'courseTable.courseTable.getWeekItemsForWx');
    // app.get('/courseTable/getWeeklyDetails', 'courseTable.courseTable.getWeeklyDetails');
  app.get('/courseTable/getTeacherCourseTable', 'courseTable.courseTable.getTeacherCourseTable');
  app.get('/courseTable/getStudentAll', 'courseTable.courseTable.getStudentAll');
  app.get('/courseTable/getStudentByTableItemId', 'courseTable.courseTable.getStudentByTableItemId');
  app.get('/courseTable/getByTeacherId1', 'courseTable.courseTable.getByTeacherId1');
  app.get('/courseTable/getList', 'courseTable.courseTable.getList');
  app.get('/courseTable/getTermTimeTag', 'courseTable.courseTableDetail.getTermTimeTag');
  app.get('/courseTable/getClassTimeTimeTag', 'courseTable.courseTableDetail.getClassTimeTimeTag');
  app.post('/courseTable/delete', 'courseTable.courseTableDetail.delete');
    // app.get('/courseTable/getInfo', 'courseTable.courseTableDetail.getInfo');
  app.post('/courseTable/addDetail', 'courseTable.courseTableDetail.addDetail');
  app.post('/courseTable/getListByTeacherIdAndTermId', 'courseTable.courseTableDetail.getListByTeacherIdAndTermId');
  app.get('/courseTable/getnLeaveLengthAndnChangeClassLengthBycourseTableItemId', 'courseTable.courseTableDetail.getnLeaveLengthAndnChangeClassLengthBycourseTableItemId');
    // app.get('/courseTable/getListByTeacherId', 'courseTable.courseTableDetail.getListByTeacherId');
  app.get('/courseTable/getListBytermIdAndOpenEnrollment', 'courseTable.courseTableDetail.getListBytermIdAndOpenEnrollment');
  app.post('/courseTable/delete', 'courseTable.courseTableDetail.delete');
  app.get('/courseTable/getInfo', 'courseTable.courseTableDetail.getInfo');
  app.get('/courseTable/getClassTimeClasstransfer', 'courseTable.courseTableDetail.getClassTimeClasstransfer');
  app.get('/courseTable/getClassTimeClasstransferByTermId', 'courseTable.courseTableDetail.getClassTimeClasstransferByTermId');
  app.get('/courseTable/getSuspendClassesInfoByCourseTableDetailStudentId', 'courseTable.courseTableDetail.getSuspendClassesInfoByCourseTableDetailStudentId');
  app.post('/courseTable/changeOpen', 'courseTable.courseTableDetail.changeOpen');
  app.post('/courseTable/suspendClasses', 'courseTable.courseTableDetail.suspendClasses');
  app.post('/courseTable/transferTheClass', 'courseTable.courseTableDetail.transferTheClass');
  app.post('/courseTable/getSuspension', 'courseTable.courseTableDetail.getSuspension');
  app.post('/courseTable/clearCourse', 'courseTable.courseTableDetail.clearCourse');
  app.get('/courseTable/getSelectClass', 'courseTable.courseTableDetail.getSelectClass');
  app.get('/courseTable/getSelectClassRecord', 'courseTable.courseTableDetail.getSelectClassRecord');
  app.get('/courseTable/getClassTimeClassLeave', 'courseTable.courseTableDetail.getClassTimeClassLeave');
  app.post('/courseTable/addClassLeave', 'courseTable.courseTableLeave.addClassLeave');
  app.get('/courseTable/getAllSuspensionAndClasstransfer', 'courseTable.courseTableDetail.getAllSuspensionAndClasstransfer');
  app.get('/courseTable/getAllSuspensionAndClasstransfer', 'courseTable.courseTableDetail.getAllSuspensionAndClasstransfer');
  app.get('/courseTable/getTerm', 'courseTable.courseTableDetail.getTerm');
  app.get('/courseTable/getListByTeacherId', 'courseTable.courseTableDetail.getListByTeacherId');
  app.get('/courseTable/getByDetailId', 'courseTable.courseTableDetail.getById');
  app.post('/courseTable/classTimeClassTransfer', 'courseTable.courseTableDetail.classTimeClassTransfer');
  app.get('/courseTable/getCourTableDetailBystudentId', 'courseTable.courseTableDetail.getCourTableDetailBystudentId');
  app.get('/courseTable/getMyAllCourseByStudentIdAndTermId', 'courseTable.courseTableDetail.getMyAllCourseByStudentIdAndTermId');
  app.get('/courseTable/getTeacherList', 'term.getTeacherList');
  app.get('/courseTable/getNumberOfChangeClass', 'courseTable.courseTableDetail.getNumberOfChangeClassByCourseTableDetailIdAndStudentId');
  app.get('/courseTable/getCourseTableDetailByFilter', 'courseTable.courseTableDetail.getCourseTableDetailByFilter');
  app.get('/courseTable/getByDetailItemId', 'courseTable.courseTableItem.getById');
  app.get('/courseTable/getClassTimeLeaveRecord', 'courseTable.courseTableItem.getClassTimeLeaveRecord');
  app.get('/courseTable/getListEvenClassDetail', 'courseTable.courseTableItem.getListEvenClassDetail');
  app.get('/courseTable/getApplicableCourse', 'courseTable.courseTableDetail.getApplicableCourse');
  app.get('/courseTable/getApplicableCourse', 'courseTable.courseTableDetail.getApplicableCourse');
  app.get('/courseTable/getApplicableCourseByCourseNameAndTermId', 'courseTable.courseTableDetail.getApplicableCourseByCourseNameAndTermId');
  app.get('/courseTable/getApplicableCourseByCourseNameAndTeacherNameAndTermId', 'courseTable.courseTableDetail.getApplicableCourseByCourseNameAndTeacherNameAndTermId');
  app.get('/courseTable/getApplicableCourseByTermIdAndCourseNameAndTercherNameAndWeek', 'courseTable.courseTableDetail.getApplicableCourseByTermIdAndCourseNameAndTercherNameAndWeek');
  app.get('/courseTable/getApplicableCourseByTermId', 'courseTable.courseTableDetail.getApplicableCourseByTermId');

  app.post('/courseTable/addItem', 'courseTable.courseTableItem.addItem');
  app.post('/courseTable/classTransfer', 'courseTable.courseTableItem.classTransfer');
  app.post('/courseTable/uodate', 'courseTable.courseTableItem.update');
  app.post('/courseTable/deleteItem', 'courseTable.courseTableItem.deleteItem');
  app.post('/courseTable/signUpClassTimeClass', 'courseTable.courseTableItem.signUpClassTimeClass');
  app.post('/courseTable/checkWorkSubmit', 'courseTable.courseTableItem.checkWorkSubmit');
  app.post('/courseTable/submitBookingCourse', 'courseTable.courseTableItem.submitBookingCourse');
  app.post('/courseTable/bookingCourseCaculById', 'courseTable.courseTableItem.bookingCourseCaculById');
  app.get('/courseTable/getBookingCourseList', 'courseTable.courseTableItem.getBookingCourseList');
  app.get('/courseTable/getBookingCourseById', 'courseTable.courseTableItem.getBookingCourseById');
  app.get('/courseTable/getWeekItems', 'courseTable.courseTableItem.getWeekItems');
  app.get('/courseTable/getClassBerforsuspendClasses', 'courseTable.courseTableItem.getClassBerforsuspendClasses');
  app.get('/courseTable/getWeekItemsForStudent', 'courseTable.courseTableItem.getWeekItemsForStudent');
  app.get('/courseTable/levelLength', 'courseTable.courseTableItem.levelLength');
  app.get('/courseTable/getBookingCourses', 'courseTable.courseTableItem.getBookingCourses');
  app.get('/courseTable/getBookingCourseItem', 'courseTable.courseTableItem.getBookingCourseItem');
  app.get('/courseTable/getBeforeSuspendClassInfoByCourseTableDetailStudentId', 'courseTable.courseTableDetail.getBeforeSuspendClassInfoByCourseTableDetailStudentId');
  app.get('/courseTable/getBookingCourseTeacher', 'courseTable.courseTableItem.getBookingCourseTeacher');
  app.get('/courseTable/getBookingCourse', 'courseTable.courseTableItem.getBookingCourse');
  app.get('/courseTable/getBookingCourseTime', 'courseTable.courseTableItem.getBookingCourseTime');
  app.get('/courseTable/getBookingCourseOtherTime', 'courseTable.courseTableItem.getBookingCourseOtherTime');
  app.get('/courseTable/getWeekById', 'courseTable.courseTableItem.getWeekById');
  app.get('/courseTable/checkWork', 'courseTable.courseTableItem.checkWork');
  app.get('/courseTable/getCommentDetail', 'courseTable.courseTableItem.getCommentDetail');
  app.get('/courseTable/getChangeClassInfo', 'courseTable.courseTableItem.getChangeClassInfo');
  app.get('/courseTable/getClassTimeLeaveInfo', 'courseTable.courseTableItem.getClassTimeLeaveInfo');

  app.post('/courseTableLeave/addLeaveForTeacher', 'courseTable.courseTableLeaveForTeacher.addLeave');
  app.post('/courseTableLeave/addClassTimeLeave', 'courseTable.courseTableLeaveForTeacher.addClassTimeLeave');
  
  
  app.get('/courseTableLeave/getLeaveData', 'courseTable.courseTableLeave.getLeaveData');
  app.post('/courseTableLeave/addLeave', 'courseTable.courseTableLeave.addLeave');
  app.get('/courseTableLeave/getLeaveDataForStudent', 'courseTable.courseTableLeave.getLeaveDataForStudent');
  app.get('/courseTableLeave/getLeaveDetail', 'courseTable.courseTableLeave.getLeaveDetail');
  app.get('/courseTableLeave/getList', 'courseTable.courseTableLeave.getList');
  app.get('/courseTableLeave/getListBystudentIdAndTermId', 'courseTable.courseTableLeave.getListBystudentIdAndTermId');

  app.get('/courseTableChangeClass/getChangeClassData', 'courseTable.courseTableChangeClass.getChangeClassData');
  app.post('/courseTableChangeClass/getChangeClassDataForStudentByTeacherId', 'courseTable.courseTableChangeClass.getChangeClassDataForStudentByTeacherId');
  app.post('/courseTableChangeClass/getMakeupDataForStudentByTeacherId', 'courseTable.courseTableChangeClass.getMakeupDataForStudentByTeacherId');
  app.post('/courseTableChangeClass/addChangeClass', 'courseTable.courseTableChangeClass.addChangeClass');
  app.post('/courseTableChangeClass/addMakeup', 'courseTable.courseTableChangeClass.addMakeup');
  app.get('/courseTableChangeClass/getChangeClassDataForStudent', 'courseTable.courseTableChangeClass.getChangeClassDataForStudent');
  app.get('/courseTableChangeClass/getMakeupDataForStudent', 'courseTable.courseTableChangeClass.getMakeupDataForStudent');
  app.get('/courseTableChangeClass/getLeaveDetail', 'courseTable.courseTableChangeClass.getLeaveDetail');
  app.get('/courseTableChangeClass/getList', 'courseTable.courseTableChangeClass.getList');
  app.get('/courseTableChangeClass/getListByTermIdAndstundetId', 'courseTable.courseTableChangeClass.getListByTermIdAndstundetId');
  app.get('/courseTableChangeClass/getChangeClassByCourseTableDetailIdAndStudentId', 'courseTable.courseTableChangeClass.getChangeClassByCourseTableDetailIdAndStudentId');

  app.post('/courseTableChangeClassForTeacher/addChangeClass', 'courseTable.courseTableChangeClassForTeacher.addChangeClass');
  app.get('/courseTableChangeClassForTeacher/getBeforeChangeClassDate', 'courseTable.courseTableChangeClassForTeacher.getBeforeChangeClassDate');
  app.get('/courseTableChangeClassForTeacher/getList', 'courseTable.courseTableChangeClassForTeacher.getList');
  app.get('/courseTableChangeClassForTeacher/getListByTeacherIdAndtermId', 'courseTable.courseTableChangeClassForTeacher.getListByTeacherIdAndtermId');
  app.get('/courseTableChangeClassForTeacher/getListByCourseTableDetailIdAndTeacherId', 'courseTable.courseTableChangeClassForTeacher.getListByCourseTableDetailIdAndTeacherId');
    // app.get('/courseTableLeave/getSwitchData', 'courseTable.courseTableLeave.getSwitchData');
    // app.post('/courseTableLeave/addLeave', 'courseTable.courseTableLeave.addLeave');
    // app.get('/courseTableLeave/getSwitchDataForStudent', 'courseTable.courseTableLeave.getSwitchDataForStudent');
    // app.get('/courseTableLeave/getSwitchDetail', 'courseTable.courseTableLeave.getSwitchDetail');
    // app.get('/courseTableLeave/getList', 'courseTable.courseTableLeave.getList');
};
